name: Artifact Test

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create txt
        run: echo "Hello, world!" > hello.txt
      - name: Upload hello.txt
        uses: actions/upload-artifact@v4
        with:
          name: hello-txt-file
          path: hello.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download hello.txt
        uses: actions/download-artifact@v4
        with:
          name: hello-txt-file
          path: hello.txt
      - name: Print hello.txt
        run: cat hello.txt

